controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

# api/config/routes.yaml
api_login_check:
    path: /authentication_token
    methods: ['POST']

api_forgot_password:
    path: /api/forgot-password
    methods: ['POST']
    controller: App\Controller\Security\AuthController::forgotPassword

api_reset_password:
    path: /api/reset-password
    methods: ['GET']
    controller: App\Controller\Security\AuthController::resetPassword

api_reset_password_done:
    path: /api/reset-password
    methods: ['POST']
    controller: App\Controller\Security\AuthController::sendMailPasswordIsReinit
